version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@3.2.0
  jq: circleci/jq@2.2.0

executors:
  node-executor:
    docker:
      - image: cimg/node:18.12.1

jobs:
  init:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-cli/setup
      - jq/install
      - attach_workspace:
          at: .
      - run:
          name: Get cluster info
          command: ./script.sh
      - run:
          name: Associate cluster
          command: |
            aws ecs put-cluster-capacity-providers \
              --cluster "${ECS_CLUSTER_NAME}" \
              --capacity-providers FARGATE FARGATE_SPOT  \
              --default-capacity-provider-strategy capacityProvider=FARGATE,weight=1 capacityProvider=FARGATE_SPOT,weight=1\
              --region ${AWS_DEFAULT_REGION}
  aws-setup:
    executor: aws-cli/default
    working_directory: ~/node/backend_app
    steps:
      - aws-cli/setup:
          profile-name: default
      - persist_to_workspace:
          root: ~/node/backend_app
          paths:
            - .
  build-migration-image:
    executor:
      name: aws-ecr/default
      use-docker-layer-caching: true
    working_directory: ~/node/backend_app
    environment:
      ACCOUNT_URL: $account_id.dkr.ecr.$region.amazonaws.com
    steps:
      - attach_workspace:
          at: .
      - aws-ecr/build-and-push-image:
          account-url: ACCOUNT_URL
          dockerfile: Dockerfile
          profile-name: default
          region: AWS_DEFAULT_REGION
          repo: $repo
          tag: "migration-latest,migration-${CIRCLE_BUILD_NUM}"
  run-migrations:
    executor: aws-cli/default
    working_directory: ~/node/backend_app
    steps:
      - aws-cli/setup
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - aws-ecs/run-task:
          cluster: $CLUSTER_NAME
          capacity-provider-strategy: capacityProvider=FARGATE,weight=1 capacityProvider=FARGATE_SPOT,weight=1
          launch-type: ""
          task-definition: webapp-fargate-task
          subnet-ids: "$SUBNET_ONE, $SUBNET_TWO"
          security-group-ids: $SECURITY_GROUP_IDS
          assign-public-ip: ENABLED
          count: 4

workflows:
  version: 2
  build-deploy-master:
    jobs:
      - init
      - aws-setup:
          filters:
            branches:
              only:
                - master
          context: master
      - run-migrations:
          filters:
            branches:
              only:
                - master
          context: master
          requires:
            - aws-setup
            - build-migration-image
      - build-migration-image:
          filters:
            branches:
              only:
                - master
          context: master
          requires:
            - aws-setup