version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  verify-deployment:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Get last task definition
          command: >
            TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition contact-app \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
            "$BASH_ENV"
      - aws-ecs/verify-revision-is-deployed:
          family: "contact-app"
          cluster: "contact-app-cluster"
          service-name: "contact-app-service"
          task-definition-arn: "${TASK_DEFINITION_ARN}"

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          registry-id: ACCOUNT_ID
          aws-cli-version: latest
          dockerfile: Dockerfile
          executor: aws-ecr/default
          region: "${AWS_DEFAULT_REGION}"
          repo: "${MY_REPO}"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "contact-app"
          cluster: "contact-app-cluster"
          service-name: "contact-app-service"
          container-image-name-updates: "container=contact-app,tag=${CIRCLE_SHA1}"
      - verify-deployment:
          requires:
            - aws-ecs/deploy-service-update
