version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@3.2.0
  shellcheck: circleci/shellcheck@2.2
  jq: circleci/jq@2.2.0

executors:
  node-executor:
    docker:
      - image: cimg/node:18.12.1

jobs:
  aws-cli-setup:
    executor: aws-cli/default
    working_directory: ~/node/backend_app
    steps:
      - aws-cli/setup:
          profile-name: default
      - persist_to_workspace:
          root: ~/node/backend_app
          paths:
            - .
  build:
    executor:
      name: aws-ecr/default
      use-docker-layer-caching: true
    working_directory: ~/node/backend_app
    environment:
      ACCOUNT_URL: $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    steps:
      - attach_workspace:
          at: .
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: ACCOUNT_URL
          dockerfile: Dockerfile
          profile-name: default
          region: AWS_DEFAULT_REGION
          repo: contact-repository
          tag: "migration-latest,migration-${CIRCLE_BUILD_NUM}"
  before-deploy:
    executor: aws-cli/default
    working_directory: ~/node/backend_app
    steps:
      - jq/install
      - attach_workspace:
          at: .
      - run:
          name: Get cluster info
          command: |
            SERVICES_OBJ=$(aws ecs describe-services --cluster "${ECS_CLUSTER_NAME}" --services "${ECS_SERVICE_NAME}")
            VPC_CONF_OBJ=$(echo $SERVICES_OBJ | jq '.services[].networkConfiguration.awsvpcConfiguration')
            SUBNET_ONE=$(echo "$VPC_CONF_OBJ" | jq '.subnets[0]')
            SUBNET_TWO=$(echo "$VPC_CONF_OBJ" | jq '.subnets[1]')
            SECURITY_GROUP_IDS=$(echo "$VPC_CONF_OBJ" | jq '.securityGroups[0]')
            CLUSTER_NAME=$(echo "$SERVICES_OBJ" | jq '.services[].clusterArn')
            echo "export SUBNET_ONE=$SUBNET_ONE" >> "$BASH_ENV"
            echo "export SUBNET_TWO=$SUBNET_TWO" >> "$BASH_ENV"
            echo "export SECURITY_GROUP_IDS=$SECURITY_GROUP_IDS" >> "$BASH_ENV"
            echo "export CLUSTER_NAME=$CLUSTER_NAME" >> "$BASH_ENV"
      - run:
          name: Associate cluster
          command: |
            aws ecs put-cluster-capacity-providers \
              --cluster "${ECS_CLUSTER_NAME}" \
              --capacity-providers FARGATE FARGATE_SPOT  \
              --default-capacity-provider-strategy capacityProvider=FARGATE,weight=1 capacityProvider=FARGATE_SPOT,weight=1\
              --region ${AWS_DEFAULT_REGION}

workflows:
  version: 2
  build-deploy-main:
    jobs:
      - aws-cli-setup:
          filters:
            branches:
              only:
                - main
          context: main
      - before-deploy:
          filters:
            branches:
              only:
                - main
          context: main
          requires:
            - awscli--setup
            - build
      - build:
          filters:
            branches:
              only:
                - main
          context: main
          requires:
            - aws-cli-setup
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          cluster: $CLUSTER_NAME
          launch-type: "FARGATE"
          task-definition: contact-app
          subnet-ids: "$SUBNET_ONE, $SUBNET_TWO"
          security-group-ids: $SECURITY_GROUP_IDS
          assign-public-ip: ENABLED
          count: 1
