version: 2.1 # 2.1 config required to use orbs

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@3.2.0

jobs:
  build-image:
    executor:
      name: aws-ecr/default
      use-docker-layer-caching: true
    working_directory: ~/node/backend_app
    environment:
      ACCOUNT_URL: "545108995501.dkr.ecr.ap-southeast-3.amazonaws.com"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: ACCOUNT_URL
          dockerfile: Dockerfile
          profile-name: default
          region: AWS_DEFAULT_REGION
          repo: "contact-repository"
          tag: "${CIRCLE_SHA1}"
  verify-deployment:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_DEFAULT_REGION
      - run:
          name: Get last task definition
          command: >
            TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition ${MY_APP_PREFIX}-service \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
            "$BASH_ENV"
      - aws-ecs/verify-revision-is-deployed:
          family: "${MY_APP_PREFIX}-service"
          cluster: "${MY_APP_PREFIX}-cluster"
          task-definition-arn: "${TASK_DEFINITION_ARN}"

workflows:
  build-and-deploy:
    jobs:
      - build-image
      - aws-ecs/deploy-service-update: # orb built-in job
          requires:
            - build-image
          family: "contact-app-service"
          cluster: "contact-app-cluster"
          container-image-name-updates: "container=contact-app-service,tag=${CIRCLE_SHA1}"
      - verify-deployment:
          requires:
            - aws-ecs/deploy-service-update
